### ISSUE TITLE
Solution from Docker hub does not work.

### ISSUE THREAD

**Issue by victor-shelepen** [berejant/nomeroff-api#1]
I tried to up to run your application using a container from docker hub. It did not work. I had the following error.
```bash
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 39700)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/http_server.py", line 70, in do_POST
    number = detect(post_body)
  File "/http_server.py", line 49, in detect
    targetBoxes = detector.detect_bbox(img)
  File "/nomeroff-net/NomeroffNet/YoloV5Detector.py", line 70, in detect_bbox
    img_shape = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
----------------------------------------
```
I will be glad if you share your solution.

**Comment by xVaDiMx** [comment]
Don't forget to add **@**

curl http://localhost:8020/ -X POST --data-binary **@**/path/to/image/jpg
